<?php
define('_MARQUEE_TITLE', 'Marquee');
define('_MARQUEE_ADD_CONTENT', 'Please enter the content of the marquee');
define('_MARQUEE_FONT_SIZE', 'Font size:');
define('_MARQUEE_FONT_COLOR', 'Font color:');
define('_MARQUEE_BG_COLOR', 'Background color:');
define('_MARQUEE_PADDING', 'Padding');
define('_MARQUEE_BORDER_SIZE', 'Border size:');
define('_MARQUEE_BORDER_TYPE', 'Border type:');
define('_MARQUEE_SOLID', 'solid');
define('_MARQUEE_DOTTED', 'dotted');
define('_MARQUEE_DASHED', 'dashed');
define('_MARQUEE_DOUBLE', 'double');
define('_MARQUEE_GROOVE', 'groove');
define('_MARQUEE_RIDGE', 'ridge');
define('_MARQUEE_INSET', 'inset');
define('_MARQUEE_OUTSET', 'outset');
define('_MARQUEE_BORDER_COLOR', 'Border color:');
define('_MARQUEE_ADD_TARGET', 'target');
define('_MARQUEE_ADD_TARGET_SELF', 'self');
define('_MARQUEE_ADD_TARGET_BLANK', 'blank');
define('_MARQUEE_ADD_URL', 'Please enter a URL (unnecessary)');
