<?php
define('_LINK_TITLE', '一般連結');
define('_LINK_ADD_URL', '請輸入網址');
define('_LINK_ADD_TEXT', '請輸入選項文字');
define('_LINK_SHOW_TYPE', '顯示類型：');
define('_LINK_DEFAULT', '預設');
define('_LINK_UL', '無序清單');
define('_LINK_OL', '數字清單');
define('_LINK_NONE', '僅換行');
define('_LINK_TABLE', '表格');
define('_LINK_IMAGE', '圖片');
define('_LINK_ADD_TARGET', '開啟位置');
define('_LINK_ADD_TARGET_SELF', '本視窗');
define('_LINK_ADD_TARGET_BLANK', '新視窗');
define('_LINK_ITEM_CSS', '自訂選項樣式：');
define('_LINK_IMG_CSS', '自訂圖片樣式：');
define('_LINK_TXT_CSS', '自訂文字樣式：');
define('_LINK_HIDE_PIC', '隱藏圖片：');
define('_LINK_PIC_WIDTH', '圖片統一寬度：');
define('_LINK_PIC_DESC', '（設 0 為使用圖片原始寬度）');
